export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const FETCH_STUDENT_REQUEST = "FETCH_STUDENT_REQUEST";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_STUDENT_ERROR = "FETCH_STUDENT_ERROR";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL ="CLOSE_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL";
export const UPDATE_STUDENT = "UPDATE_STUDENT";

